---
title: Visualising categorical data
author: Nicole Odo
date: '2021-05-18'
slug: visualising-categorical-data
categories: []
tags: []
---
## Bar plot
```{r}
library(openintro)
library(tidyverse)
loans <- loans_full_schema %>%
  select(loan_amount, interest_rate, term, grade, 
         state, annual_income, homeownership, debt_to_income)
glimpse(loans)

ggplot(loans, aes(x = homeownership)) +
  geom_bar()
```
```{r}
library(openintro)
library(tidyverse)
ggplot(loans, aes(x = homeownership, 
                  fill = grade)) +
  geom_bar()
```
```{r}
library(openintro)
library(tidyverse)
ggplot(loans, aes(x = homeownership, 
                  fill = grade)) +
  geom_bar(position="fill")
```
## Customizing bar plots
```{r}
library(openintro)
library(tidyverse)
ggplot(loans, aes(y = homeownership,
                  fill = grade)) +
  geom_bar(position = "fill") +
  labs(
    x = "Proportion",
    y = "Homeownership",
    fill = "Grade",
    title = "Grades of Lending Club loans",
    subtitle = "and homeownership of lendee"
  )
```
## Ridge plots
```{r}
library(ggridges)
library(tidyverse)
ggplot(loans, aes(x = loan_amount, y = grade, fill = grade, color = grade)) + 
  geom_density_ridges(alpha = 0.5)
```