---
title: Data Wrangling using Tidyverse
author: Nicole Odo
date: '2021-05-25'
slug: data-wrangling-using-tidyverse
categories:
  - tidyverse
tags: []
---

## Import the Hotels.csv file
```{r warning=FALSE}
# getwd() in the console will show your current working directory
#can either put the CSV file directly into the post folder you're working in OR Environment - Import Data Set - From Text(readr)
library(tidyverse)
hotels <- read_csv("hotels.csv")
head(hotels)
names(hotels)
```
## Select a variable
```{r}
select(hotels, lead_time)
#takes the data frame hotels, and selects the variable you've specified and creates  a new data frame

#select multiple columns
#select(hotels, hotel, lead_time)

#same output as above
hotels%>%
  select(hotel,lead_time) %>%
  arrange(desc(lead_time)) #arranges it by lead time instead of default of the format of the file. Takes input from the previous step, then executes this command
#desc puts in descending order. Without it, it goes to ascending order

# how pipes work. Think of them as a sequence of actions
# park(drive(start_car(find("keys")), to="work")
# piping looks like:
# find("keys")%?%
# start_car() %?%
# drive(to="work") %?%

# cannot use + in dplyr and cannot use %>% in ggplot either
```

## Select a range of variables
```{r}
hotels %>%
  select(hotel:arrival_date_month)

hotels %>%
  select(starts_with("arrival")) #selects all variables that start with word arrival
```

## Select a range of rows / cases
```{r}
hotels %>%
  slice (c(1,5,8,10)) #or slice(1:5)

hotels %>%
  filter(hotel == "City Hotel")

hotels %>%
  filter( 
    adults == 0,
    children >= 1
    ) %>% 
  select(adults, babies, children)

# bookings with no adults and some children or babies in the room
hotels %>%
  filter( 
    adults == 0,     
    children >= 1 & babies >= 1     # | means or
    ) %>%
  select(adults, babies, children)
```

## Summarizing
```{r}
# count for multiple variables
hotels %>%
  count(hotel, market_segment)

# hotel type first
hotels %>%
  count(hotel, market_segment)

# market segment first
hotels %>%
  count(market_segment, hotel)

```

## Mutation
```{r}
# mutate to add a new variable
hotels %>%
  mutate(little_ones = children + babies) %>%
  select(children, babies, little_ones) %>%
  arrange(desc(little_ones))

# mutate to add a new variable
little_ones <- hotels

little_ones %<>%
  mutate(little_ones = children + babies) %>%
  select(children, babies, little_ones) %>%
  arrange(desc(little_ones))
```
## Summary
```{r}
# mean average daily rate for all bookings
hotels %>%
  summarise(mean_adr = mean(adr))

# mean average daily rate for all booking at city and resort hotels
summay <- hotels %>%
  group_by(hotel) %>%
  summarise(mean_adr = mean(adr))
summary

```

