<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.83.1" />


<title>A03 - NicoleOdo - Fundamentals of Analytics</title>
<meta property="og:title" content="A03 - NicoleOdo - Fundamentals of Analytics">


  <link href='/favicon.ico' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/Photo.jpeg"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/nicoleodo">GitHub</a></li>
    
    <li><a href="https://www.linkedin.com/in/nicole-odo-a86a07123/?originalSubdomain=ca">LinkedIn</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">6 min read</span>
    

    <h1 class="article-title">A03</h1>

    
    <span class="article-date">2021-06-03</span>
    

    <div class="article-content">
      
<script src="/2021/06/03/a03/index_files/header-attrs/header-attrs.js"></script>


<p>We are exploring a data set that summarizes lego sales. It provides an information on who the customer was, their age, what theme of lego they bought, price, and several other variables. This allows us to analyze the data for trends and to gain insight into commonly purchased lego sets.</p>
<div id="what-are-the-three-most-common-first-names-of-customers" class="section level2">
<h2>1. What are the three most common first names of customers?</h2>
<pre><code>## # A tibble: 211 x 2
##    first_name     n
##    &lt;chr&gt;      &lt;int&gt;
##  1 Jackson       13
##  2 Jacob         11
##  3 Joseph        11
##  4 Michael       10
##  5 Audrey         8
##  6 Connor         8
##  7 Kaitlyn        8
##  8 Lucas          8
##  9 Amanda         7
## 10 Joshua         7
## # … with 201 more rows</code></pre>
<p>The three most common first names are Jackson, Jacob and Joseph.</p>
</div>
<div id="what-are-the-three-most-common-themes-of-lego-sets-purchased" class="section level2">
<h2>2. What are the three most common themes of lego sets purchased?</h2>
<pre><code>## # A tibble: 25 x 2
##    theme            n
##    &lt;chr&gt;        &lt;int&gt;
##  1 Star Wars       75
##  2 Nexo Knights    64
##  3 Gear            55
##  4 Mixels          55
##  5 City            45
##  6 Friends         42
##  7 Ninjago         38
##  8 Duplo           35
##  9 Bionicle        34
## 10 Creator         25
## # … with 15 more rows</code></pre>
<p>The three most common themes of lego sets purchased are Star Wars, Nexo Knights, and a tie for Gear and Mixels.</p>
</div>
<div id="among-the-most-common-theme-of-lego-sets-purchased-what-is-the-most-common-subtheme" class="section level2">
<h2>3. Among the most common theme of lego sets purchased, what is the most common subtheme?</h2>
<pre><code>## # A tibble: 11 x 3
##    theme     subtheme                      n
##    &lt;chr&gt;     &lt;chr&gt;                     &lt;int&gt;
##  1 Star Wars The Force Awakens            13
##  2 Star Wars Buildable Figures            10
##  3 Star Wars MicroFighters                 9
##  4 Star Wars Episode V                     8
##  5 Star Wars Episode III                   6
##  6 Star Wars Original Content              6
##  7 Star Wars Battlefront                   5
##  8 Star Wars Episode IV                    2
##  9 Star Wars Rebels                        2
## 10 Star Wars Seasonal                      1
## 11 Star Wars Ultimate Collector Series     1</code></pre>
<p>From the results of the question prior, we know that Star Wars was the most common theme of lego sets purchased. Of that theme, the most common subtheme is The Force Awakens.</p>
</div>
<div id="create-a-new-variable-called-age_group-and-group-the-ages-into-categories" class="section level2">
<h2>4. Create a new variable called “age_group” and group the ages into categories</h2>
<pre><code>## # A tibble: 620 x 15
##    first_name last_name    age phone_number set_id number theme  subtheme   year
##    &lt;chr&gt;      &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;     &lt;dbl&gt;
##  1 Kimberly   Beckstead     24 216-555-2549  24701 76062  DC Co… Mighty M…  2018
##  2 Neel       Garvin        35 819-555-3189  25626 70595  Ninja… Rise of …  2018
##  3 Neel       Garvin        35 819-555-3189  24665 21031  Archi… &lt;NA&gt;       2018
##  4 Chelsea    Bouchard      41 &lt;NA&gt;          24695 31048  Creat… &lt;NA&gt;       2018
##  5 Chelsea    Bouchard      41 &lt;NA&gt;          25626 70595  Ninja… Rise of …  2018
##  6 Chelsea    Bouchard      41 &lt;NA&gt;          24721 10831  Duplo  &lt;NA&gt;       2018
##  7 Bryanna    Welsh         19 &lt;NA&gt;          24797 75138  Star … Episode V  2018
##  8 Bryanna    Welsh         19 &lt;NA&gt;          24701 76062  DC Co… Mighty M…  2018
##  9 Caleb      Garcia-Wi…    37 907-555-9236  24730 41115  Frien… &lt;NA&gt;       2018
## 10 Caleb      Garcia-Wi…    37 907-555-9236  25611 21127  Minec… Minifig-…  2018
## # … with 610 more rows, and 6 more variables: name &lt;chr&gt;, pieces &lt;dbl&gt;,
## #   us_price &lt;dbl&gt;, image_url &lt;chr&gt;, quantity &lt;dbl&gt;, AgeGroup &lt;chr&gt;</code></pre>
</div>
<div id="what-is-the-probability-a-randomly-selected-customer" class="section level2">
<h2>5. What is the probability a randomly selected customer?</h2>
<div id="a.-is-in-the-19---25-age-group" class="section level3">
<h3>a. Is in the 19 - 25 age group?</h3>
<pre><code>## # A tibble: 1 x 3
##   AgeGroup     n  prob
##   &lt;chr&gt;    &lt;int&gt; &lt;dbl&gt;
## 1 19 - 25    129 0.208</code></pre>
<p>There is a 20.8% chance that a randomly selected customer will be in the 19 - 25 age group.</p>
</div>
<div id="b.-is-in-the-19---25-age-group-and-purchased-a-duplo-theme-set" class="section level3">
<h3>b. Is in the 19 - 25 age group and purchased a Duplo theme set?</h3>
<pre><code>##   AgeGroup   n      prob theme n       prob
## 1  19 - 25 129 0.2080645 Duplo 9 0.06976744</code></pre>
<pre><code>## [1] 0.01451613</code></pre>
<p>The probability of a customer being in the 19 - 25 years age range AND purchased a Duplo themed set is 1.45%.</p>
</div>
<div id="c.-is-in-the-19---25-age-group-given-they-purchased-a-duplo-theme-set" class="section level3">
<h3>c. Is in the 19 - 25 age group given they purchased a Duplo theme set?</h3>
<pre><code>## # A tibble: 1 x 3
##   AgeGroup     n  prob
##   &lt;chr&gt;    &lt;int&gt; &lt;dbl&gt;
## 1 19 - 25      9 0.257</code></pre>
<p>Given that the customer purchased a Duplo theme lego set, there is a 25.7% chance that they are in the 19 - 25 age range.</p>
</div>
</div>
<div id="which-age-group-has-purchased-the-largest-number-of-lego-sets-how-many-did-they-purchase" class="section level2">
<h2>6. Which age group has purchased the largest number of lego sets? How many did they purchase?</h2>
<pre><code>## # A tibble: 5 x 2
##   AgeGroup     quantity
##   &lt;chr&gt;           &lt;dbl&gt;
## 1 18 and under       45
## 2 19 - 25           174
## 3 26 - 35           267
## 4 36 - 50           313
## 5 51 and over        92</code></pre>
<p>The age group that purchased the largest number of lego sets is the 36 - 50 years, with a total of 313 sets bought.</p>
</div>
<div id="which-age-group-has-spent-the-most-money-on-legos-how-much-did-they-spend" class="section level2">
<h2>7. Which age group has spent the most money on legos? How much did they spend?</h2>
<pre><code>## # A tibble: 5 x 2
##   AgeGroup     us_price
##   &lt;chr&gt;           &lt;dbl&gt;
## 1 18 and under     642.
## 2 19 - 25         3630.
## 3 26 - 35         5260.
## 4 36 - 50         6642.
## 5 51 and over     1832.</code></pre>
<p>The age group that has spent the most money on lego is also the age 36 - 50 group. They have spent a total of $6641.84</p>
</div>
<div id="custom-question-what-is-the-average-sale-price-by-age-group" class="section level2">
<h2>8. Custom question: What is the average sale price by age group?</h2>
<p><img src="/2021/06/03/a03/index_files/figure-html/unnamed-chunk-11-1.png" width="672" />
This visualization shows that not only did the 36 - 50 year olds spend the most money total on lego, they also had the highest average spend per transaction. It can also be noted that the 51 and over group had the second highest average spend per transaction, but was not the second highest spender overall.</p>
</div>
<div id="added-element-to-the-data-visualization-plot" class="section level2">
<h2>9. Added element to the data visualization plot</h2>
<p>The elements that have been changed in this plot are:</p>
<ul>
<li>The plot bars are color filled based on age group</li>
<li>The background color is now grey with white lines</li>
<li>The legend has been moved to the bottom</li>
</ul>
<p><img src="/2021/06/03/a03/index_files/figure-html/unnamed-chunk-12-1.png" width="672" />
## Discussion</p>
<p>This assignment was a great opportunity to practice newly learned skills in R Studio. It tested our abilities in extracting relevant data, and grouping variables as needed to answer the above questions. There were a few challenges encountered when attempting to extract specific data to calculate the probability questions especially, but overall, the assignment was the right amount of challenging to test our skills.</p>
<p>The analysis of the data set provides insight into the most popular lego sets, common ages of those purchasing the lego set, and how much money is spent overall on lego in the year 2018.</p>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/js/math-code.js"></script>
<script async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

