---
title: Visualizing Numerical Data
author: Nicole Odo
date: '2021-05-18'
slug: visualizing-numerical-data
categories:
  - ggplot2
tags: []
---
## Histogram
```{r}
library(openintro)
library(tidyverse)
glimpse(loans_full_schema)

loans <- loans_full_schema %>%
  select(loan_amount, interest_rate, term, grade, 
         state, annual_income, homeownership, debt_to_income)
glimpse(loans)

ggplot(loans, aes(x = loan_amount)) +
  geom_histogram()

```
```{r}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = loan_amount)) +
  geom_histogram(binwidth = 1000)
```
```{r}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = loan_amount, fill=homeownership)) +
  geom_histogram(binwidth = 5000, alpha=0.5) +labs(
    x="Loan amount ($)", 
    y="Frequency", 
    title="Amounts of Lending Club loans")
```

```{r}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = loan_amount)) +
  geom_histogram(binwidth = 20000)
```
```{r}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = loan_amount, fill=homeownership)) +
  geom_histogram(binwidth = 5000, alpha=0.5) +labs(
    x="Loan amount ($)", 
    y="Frequency", 
    title="Amounts of Lending Club loans")+facet_wrap(~homeownership,nrow=3)
```
```{r}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = loan_amount)) +geom_density()
```

## Density plots and adjusting bandwidth
```{r}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = loan_amount)) +geom_density(adjust=0.5)
```
```{r}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = loan_amount)) +geom_density(adjust=1)
```
```{r}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = loan_amount)) +geom_density(adjust=2)
```
```{r}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = loan_amount, 
                  fill = homeownership)) +
  geom_density(adjust = 2, 
               alpha = 0.5) +
  labs(
    x = "Loan amount ($)",
    y = "Density",
    title = "Amounts of Lending Club loans", 
    fill = "Homeownership"
  )
```
## Boxplot
```{r}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = interest_rate)) +
  geom_boxplot()
```
```{r}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = annual_income)) +
  geom_boxplot()
```
```{r}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = interest_rate)) +
  geom_boxplot() +
  labs(
    x = "Interest rate (%)",
    y = NULL,
    title = "Interest rates of Lending Club loans"
  ) +
  theme(
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank()
  )

```
```{r}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = interest_rate,
                  y = grade)) +
  geom_boxplot() +
  labs(
    x = "Interest rate (%)",
    y = "Grade",
    title = "Interest rates of Lending Club loans",
    subtitle = "by grade of loan"
  )

```


```{r warning=FALSE}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = debt_to_income, y = interest_rate)) +
  geom_point()

```
```{r warning=FALSE}
library(openintro)
library(tidyverse)

ggplot(loans, aes(x = debt_to_income, y = interest_rate)) +
  geom_hex()

```
```{r}
library(openintro)
library(tidyverse)

ggplot(loans %>% filter(debt_to_income < 100), 
       aes(x = debt_to_income, y = interest_rate)) +
  geom_hex()

```

